/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPanel: typeof import('./src/components/AboutPanel.vue')['default']
    CodemirrorEditor: typeof import('./src/components/editor/CodemirrorEditor.vue')['default']
    CommitHistory: typeof import('./src/components/editor/CommitHistory.vue')['default']
    DifferencesPanel: typeof import('./src/components/DifferencesPanel.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FilePanel: typeof import('./src/components/file/FilePanel.vue')['default']
    FileTree: typeof import('./src/components/file/FileTree.vue')['default']
    FileTypeIcon: typeof import('./src/components/file/FileTypeIcon.vue')['default']
    FrontMatterEditor: typeof import('./src/components/editor/FrontMatterEditor.vue')['default']
    LocalFileEditor: typeof import('./src/components/editor/LocalFileEditor.vue')['default']
    MdEditor: typeof import('./src/components/editor/MdEditor.vue')['default']
    NativeFileEditor: typeof import('./src/components/editor/NativeFileEditor.vue')['default']
    OutlinePanel: typeof import('./src/components/OutlinePanel.vue')['default']
    RemoteFileEditor: typeof import('./src/components/editor/RemoteFileEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SidebarPanel: typeof import('./src/components/SidebarPanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
