// Desc: This file is used to import the icons that are used in the application.
// sort by the icon name
// 这是一个用于导入应用程序中使用的图标的文件。
// 按图标名称排序

import { library } from '@fortawesome/fontawesome-svg-core'

import {
  faAlignLeft,
  faAnglesUp,
  faAnglesDown,
  faArrowsRotate,
  faArrowUp19,
  faCalendarDays,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleQuestion,
  faClock,
  faCode,
  faCodeBranch,
  faCodeCommit,
  faCommentDollar,
  faCopy,
  faD,
  faFile,
  faFileShield,
  faFloppyDisk,
  faFolder,
  faFolderOpen,
  faGear,
  faHandshakeAngle,
  faHouseCircleCheck,
  faInbox,
  faICursor,
  faKey,
  faList,
  faM,
  faMagnifyingGlass,
  faMoon,
  faN,
  faPaste,
  faPenRuler,
  faPlus,
  faRotateLeft,
  faShirt,
  faSquareCheck,
  faSquarePen,
  faSquareXmark,
  faStar,
  faSun,
  faThumbtack,
  faThumbtackSlash,
  faTrash,
  faU,
  faUpload,
  faWonSign,
} from '@fortawesome/free-solid-svg-icons'

import { faGithub, faTumblr } from '@fortawesome/free-brands-svg-icons'

export const initFontAwesomeIcons = () => {
  library.add(
    faAlignLeft,
    faAnglesUp,
    faAnglesDown,
    faArrowsRotate,
    faArrowUp19,
    faCalendarDays,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleExclamation,
    faCircleQuestion,
    faClock,
    faCode,
    faCodeBranch,
    faCodeCommit,
    faCommentDollar,
    faCopy,
    faD,
    faFile,
    faFileShield,
    faFloppyDisk,
    faFolder,
    faFolderOpen,
    faGear,
    faInbox,
    faGithub,
    faHandshakeAngle,
    faHouseCircleCheck,
    faICursor,
    faKey,
    faList,
    faM,
    faMagnifyingGlass,
    faMoon,
    faN,
    faPaste,
    faPenRuler,
    faPlus,
    faRotateLeft,
    faShirt,
    faSquareCheck,
    faSquarePen,
    faSquareXmark,
    faStar,
    faSun,
    faThumbtack,
    faThumbtackSlash,
    faTrash,
    faTumblr,
    faU,
    faUpload,
    faWonSign,
  )
}

export default initFontAwesomeIcons
